- name: "Ursula Status"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: find keystore file
      find:
        paths: "{{geth_dir}}keystore"
      register: keystore_output

    - name: Backup Worker Nucypher Keystore locally
      become: yes
      become_user: nucypher
      fetch:
        src: "{{keystore_output.files[0].path}}"
        dest: "{{deployer_config_path}}/remote_worker_backups/"

    - name: Get public ip
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: "Request Ursula Status"
      become: yes
      uri:
        url: "https://{{ip_response.content}}:9151/status/?json=true"
        validate_certs: no
      register: status_data

    - name: Print Ursula Status Result
      debug:
        msg:
          "{{status_data.json.nickname}}\n
          staker address:        {{status_data.json.staker_address}}\n
          worker address:        {{status_data.json.worker_address}}\n
          rest url:              https://{{status_data.json.rest_url}}\n
          missing commitments:   {{status_data.json.missing_commitments}}\n
          last committed period: {{status_data.json.last_committed_period}}\n
          balances:\n
            ETH:                {{status_data.json.balances.eth}}\n
            NU:                 {{status_data.json.balances.nu}}\n
          {{inventory_hostname}}:worker address:{{status_data.json.worker_address}}\n"

    - name: "Read Ursula Log"
      become: yes
      command: docker logs ursula
      register: ursula_logs

    - name: Print Ursula Status Result
      debug:
        msg:
          "{{ursula_logs['stdout']}}"
